[pytest]
testpaths = tests
filterwarnings =
    ignore::DeprecationWarning:pandapower
    ignore:tap_dependency_table is missing:DeprecationWarning
    ignore:invalid value encountered:RuntimeWarning
    ignore::FutureWarning
