"""Phase C agent: LLM with a CVXPY solver tool.

Orchestrates the agentic EV charging workflow:
  1. The LLM receives the problem context (sessions, site cap, TOU rates)
     and the user request as a natural-language message.
  2. The LLM decides whether to call 'solve_ev_schedule':
       - Scheduling / optimization requests → tool is called.
       - What-if / constraint-change requests → tool is called with overrides
         (disabled_chargers, site_cap_kw, extra_sessions).
       - Qualitative / conceptual questions → LLM answers directly; no tool call.
  3. If the tool was called, the LLM uses the returned metrics to explain the
     outcome. If not, the LLM's direct answer is used as the explanation.
  4. The verification gate checks the answer before it is surfaced, and the
     runner carries its verdict, the usage, and the trace path out with the
     result.

If the LLM does not call the tool, AgentResult.feasible is False and the
schedule is a zero matrix; the explanation still contains the LLM's answer.

For natural-language input (no pre-built DaySessions), use run_agent_from_text().
It first calls parse_nl_problem() to extract structured session data, then runs
the normal agent pipeline. If required fields are missing, it returns a
ClarificationResult asking for the missing information and explaining reasoning.

Nothing is dropped on the way out. ``AgentResult`` carries the token accounting,
the resolved model id, the trace path, the gate's verdict, the problem that was
actually posed, and — for the text entry point — the parsed problem, so a harness
can score cost, outcome, and formulation from one returned object.
"""

from dataclasses import dataclass, field
from pathlib import Path
from typing import TYPE_CHECKING, Any, Dict, List, Optional, Union

import numpy as np

from agent.llm_agent import AgentLLMResult, run_agent_llm
from config.llm import RunRecorder, RunUsage, parse_model_spec
from config.site import SiteConfig, TOUConfig
from constraints.checker import CheckResult
from data.format.schema import DaySessions
from evaluation.outcome import GateVerdict

if TYPE_CHECKING:  # pragma: no cover - import kept out of the runtime path
    from agent.parse.parse import ParsedProblem, ParseResult


def _sum_usage(*parts: Optional[RunUsage]) -> RunUsage:
    """Add several RunUsage together, skipping the ones that are None."""
    total = RunUsage()
    for part in parts:
        if part is None:
            continue
        total.prompt_tokens += part.prompt_tokens
        total.completion_tokens += part.completion_tokens
        total.total_tokens += part.total_tokens
        total.n_llm_calls += part.n_llm_calls
        total.n_tool_calls += part.n_tool_calls
        total.wall_time_s += part.wall_time_s
        total.n_missing_usage += part.n_missing_usage
    return total


@dataclass
class ClarificationResult:
    """Returned by run_agent_from_text() when required session fields are missing.

    The parse still cost tokens, so its accounting comes out with the question.

    Attributes:
        message: Human-readable question to present to the user so they can
            supply the missing information (e.g. arrival/departure times).
        missing_fields: Field descriptions the parser could not fill.
        usage: Token accounting of the parse call(s).
        model: Resolved ``provider:model`` id used for the parse.
        trace_path: Path of the parse trace, if one was written.
        parse: The ParseResult behind the question.
    """

    message: str
    missing_fields: List[str] = field(default_factory=list)
    usage: RunUsage = field(default_factory=RunUsage)
    model: str = ""
    trace_path: Optional[Path] = None
    parse: Optional["ParseResult"] = None


@dataclass
class AgentResult:
    """Result of running the agent pipeline.

    Attributes:
        schedule: Power schedule array of shape (n_sessions, n_steps) in kW.
            Rows follow ``posed_day.sessions``, which a what-if can extend.
        total_cost_usd: Total energy cost in USD.
        peak_load_kw: Maximum total power draw across all sessions (kW).
        unmet_energy_kwh: Total unmet energy across all sessions (kWh).
        feasible: True if the schedule satisfies every constraint of the problem
            that was posed.
        explanation: Human-readable summary generated by the LLM, or the gate's
            declared-failure text when verification failed twice.
        usage: Token accounting of the agent loop.
        model: Resolved ``provider:model`` id that produced the run.
        trace_path: Path of the agent's JSON trace, if one was written.
        tool_called: True if the solver tool was invoked at least once.
        gate: The verification gate's verdict, ready to pass to
            ``evaluation.outcome.classify_outcome``. None when the model never
            called the solver and there was nothing to verify.
        gate_row: The gate's per-condition row, as stored in the trace.
        gate_attempts: Answers the gate verified: 0, 1, or 2.
        declared_failure: True when the gate declared the failure, in which case
            this result carries no schedule and no numbers.
        posed_day: The day actually solved, i.e. after any what-if override.
        posed_site: The site configuration actually solved.
        check_result: Constraint check of the schedule against the posed problem.
        tool_outputs: Every solver tool output of the episode, oldest first.
        parse: ParseResult of the natural-language parse, for the text entry
            point; None when the caller supplied a DaySessions directly.
        parse_usage: Token accounting of the parse call(s).
        parse_trace_path: Path of the parse trace, if one was written.
    """

    schedule: np.ndarray
    total_cost_usd: float
    peak_load_kw: float
    unmet_energy_kwh: float
    feasible: bool
    explanation: str
    usage: RunUsage = field(default_factory=RunUsage)
    model: str = ""
    trace_path: Optional[Path] = None
    tool_called: bool = False
    gate: Optional[GateVerdict] = None
    gate_row: Dict[str, Any] = field(default_factory=dict)
    gate_attempts: int = 0
    declared_failure: bool = False
    posed_day: Optional[DaySessions] = None
    posed_site: Optional[SiteConfig] = None
    check_result: Optional[CheckResult] = None
    tool_outputs: List[Dict[str, Any]] = field(default_factory=list)
    parse: Optional["ParseResult"] = None
    parse_usage: Optional[RunUsage] = None
    parse_trace_path: Optional[Path] = None

    @classmethod
    def from_llm_result(cls, result: AgentLLMResult, **extra: Any) -> "AgentResult":
        """Carry every field of an AgentLLMResult across, plus the parse fields."""
        return cls(
            schedule=result.schedule,
            total_cost_usd=result.total_cost_usd,
            peak_load_kw=result.peak_load_kw,
            unmet_energy_kwh=result.unmet_energy_kwh,
            feasible=result.feasible,
            explanation=result.explanation,
            usage=result.usage,
            model=result.model,
            trace_path=result.trace_path,
            tool_called=result.tool_called,
            gate=result.gate,
            gate_row=result.gate_row,
            gate_attempts=result.gate_attempts,
            declared_failure=result.declared_failure,
            posed_day=result.posed_day,
            posed_site=result.posed_site,
            check_result=result.check_result,
            tool_outputs=result.tool_outputs,
            **extra,
        )

    @property
    def parsed_problem(self) -> Optional["ParsedProblem"]:
        """The problem the parser extracted, for scoring formulation. None without a parse."""
        return self.parse.problem if self.parse is not None else None

    def total_usage(self) -> RunUsage:
        """Token accounting of the whole pipeline: the parse plus the agent loop."""
        return _sum_usage(self.parse_usage, self.usage)


def run_agent(
    day: DaySessions,
    site: SiteConfig,
    tou: TOUConfig,
    request: str = "Minimize energy cost for this day.",
    max_retries: int = 1,
    *,
    model: Optional[str] = None,
    api_key: Optional[str] = None,
    client: Optional[Any] = None,
    run_id: Optional[str] = None,
    trace_dir: Optional[Path] = None,
    write_trace: bool = True,
) -> AgentResult:
    """Run the LLM agent with CVXPY solver tool.

    Args:
        day: DaySessions with sessions and horizon.
        site: SiteConfig with power cap.
        tou: TOUConfig with TOU rates.
        request: Natural-language request sent to the LLM.
        max_retries: Passed through as max_tool_rounds; lets the LLM call the
            solver more than once if needed (default 1 → cap at 3 rounds).
        model: Model id as ``provider:model`` or a bare id; defaults to
            EV_LLM_MODEL, else ``openrouter:openai/gpt-4o``.
        api_key: Provider key; falls back to the resolved provider's env key.
        client: Pre-built client exposing ``chat.completions.create``, for tests.
        run_id: Identifier for the trace file, normally the day ("2019-06-15").
            Without it the trace is named by timestamp and a harness cannot tell
            which day a trace belongs to.
        trace_dir: Root directory for traces.
        write_trace: Set False to skip writing the trace file.

    Returns:
        AgentResult with the schedule, metrics, feasibility, LLM explanation,
        gate verdict, token usage, and trace path.
    """
    # max_retries maps to max_tool_rounds; add 2 to allow the LLM at least one
    # tool call plus a retry before the explanation turn.
    max_tool_rounds = max(3, max_retries + 2)

    result = run_agent_llm(
        day,
        site,
        tou,
        request=request,
        max_tool_rounds=max_tool_rounds,
        model=model,
        api_key=api_key,
        client=client,
        run_id=run_id,
        trace_dir=trace_dir,
        write_trace=write_trace,
    )

    return AgentResult.from_llm_result(result)


def run_agent_from_text(
    user_text: str,
    *,
    model: Optional[str] = None,
    api_key: Optional[str] = None,
    max_retries: int = 1,
    allow_inference: bool = True,
    client: Optional[Any] = None,
    run_id: Optional[str] = None,
    trace_dir: Optional[Path] = None,
    write_trace: bool = True,
) -> Union[AgentResult, ClarificationResult]:
    """Run the full agent pipeline from a natural-language problem description.

    This is the entry point for free-form user input, and the only one that
    exercises the extraction step the results table's formulation column scores.
    It performs these steps:
      1. parse_nl_problem() — extracts structured session data from user's text.
         If fields are missing AND user indicated unknowns (e.g., "I don't know"),
         uses context-aware inference. Otherwise returns ClarificationResult.
      2. run_agent_llm() — the agent loop that calls the CVXPY solver, behind the
         verification gate.

    Both steps go through ``config/llm.py``, so both are billed to the same
    provider, both are recorded, and both write a trace: the parse under the
    ``parse`` arm, the agent loop under ``agent``.

    Args:
        user_text: Free-form natural-language description of the charging problem.
            Examples:
              "I have 3 EVs. EV1 arrives at 6pm, leaves at 10pm, needs 20 kWh."
              "EV1 arrives at 6pm, I don't know when it leaves, needs about 20 kWh."
        model: Model id as ``provider:model`` or a bare id, used for the parse
            and the agent loop alike.
        api_key: Key for the resolved provider; falls back to its env key
            (OPENROUTER_API_KEY, or OPENAI_API_KEY for an ``openai:`` id).
        max_retries: Passed to run_agent() as max_retries.
        allow_inference: If True, allow context-aware inference when user
            explicitly indicates some values are unknown.
        client: Pre-built client exposing ``chat.completions.create``, used for
            both steps. For tests; when given, no key is required and none is read.
        run_id: Identifier for both trace files, normally the day.
        trace_dir: Root directory for traces.
        write_trace: Set False to skip writing trace files.

    Returns:
        AgentResult if the problem was fully specified (or inferred) and the
        solver ran, or ClarificationResult if required fields were missing.
        Either way the parse's ``usage`` comes back with it, and on an
        AgentResult ``parsed_problem`` is what a harness scores formulation
        against the ground truth with.

    Raises:
        ValueError: If no API key is available for the resolved provider. The
            parse is not silently skipped: a run with no key fails loudly rather
            than returning a result that looks like a model's.
    """
    from agent.parse.parse import parse_nl_problem, parsed_problem_to_day_site_tou

    spec = parse_model_spec(model)
    parse_recorder = RunRecorder(
        spec=spec, arm="parse", run_id=run_id or "", request=user_text
    )

    parse_result = parse_nl_problem(
        user_text,
        model=model,
        api_key=api_key,
        allow_inference=allow_inference,
        client=client,
        recorder=parse_recorder,
    )
    parse_usage = parse_recorder.finish(
        final_text=parse_result.raw_llm_response,
        status="needs_clarification" if parse_result.needs_clarification else "ok",
    )
    parse_trace_path = parse_recorder.write(trace_dir) if write_trace else None

    if parse_result.needs_clarification:
        return ClarificationResult(
            message=parse_result.clarification_message,
            missing_fields=list(parse_result.missing_fields),
            usage=parse_usage,
            model=spec.key,
            trace_path=parse_trace_path,
            parse=parse_result,
        )

    day, site, tou = parsed_problem_to_day_site_tou(parse_result.problem)  # type: ignore[arg-type]

    llm_result = run_agent_llm(
        day,
        site,
        tou,
        request=user_text,
        max_tool_rounds=max(3, max_retries + 2),
        model=model,
        api_key=api_key,
        client=client,
        run_id=run_id,
        trace_dir=trace_dir,
        write_trace=write_trace,
    )

    result = AgentResult.from_llm_result(
        llm_result,
        parse=parse_result,
        parse_usage=parse_usage,
        parse_trace_path=parse_trace_path,
    )

    # If inference was used, append notes to explanation for transparency. Not
    # when the gate declared a failure: that text reports no schedule, and a note
    # about inferred inputs must not read as one more finding about a run that
    # surfaced nothing.
    if (
        parse_result.used_inference
        and parse_result.inference_notes
        and not result.declared_failure
    ):
        result.explanation += (
            " (Note: I inferred some values based on context: "
            + "; ".join(parse_result.inference_notes)
            + ")"
        )

    return result
